'use strict';
const main=document.querySelector('#main');
const STORAGE='deutsch-a1-v2';
function emptyState(){return {version:2,done:{},mistakes:[],answers:{},pages:{},page:8};}
function validKey(key){const m=/^(\d+)-(\d+)$/.exec(key);return !!m&&!!LESSONS[Number(m[1])]?.questions[Number(m[2])];}
function cleanState(s){if(!s||typeof s!=='object'||Array.isArray(s))throw Error('Format invalide');const out=emptyState();for(const [key,a] of Object.entries(s.answers||{}))if(validKey(key)&&a&&typeof a.ok==='boolean')out.answers[key]={ok:a.ok,value:typeof a.value==='string'?a.value.slice(0,400):''};for(const[key,v]of Object.entries(s.done||{}))if(/^\d+$/.test(key)&&LESSONS[Number(key)]&&v===true)out.done[key]=true;out.mistakes=[...new Set((Array.isArray(s.mistakes)?s.mistakes:[]).filter(validKey))];for(const[key,p]of Object.entries(s.pages||{}))if(/^\d+$/.test(key)&&Number(key)>=1&&Number(key)<=255&&p&&typeof p==='object')out.pages[key]={done:p.done===true,notes:typeof p.notes==='string'?p.notes.slice(0,10000):''};if(Number.isInteger(s.page)&&s.page>=1&&s.page<=255)out.page=s.page;return out;}
let state=emptyState(),storageOK=true;
try{const data=localStorage.getItem(STORAGE)||localStorage.getItem('deutsch-a1-v1');if(data)state=cleanState(JSON.parse(data));}catch{storageOK=false;}
let current=0,tab='cours',view='book',reviewing=false,voiceReady=false;
function status(t){document.querySelector('#message').textContent=t;}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));storageOK=true;}catch{storageOK=false;status('Sauvegarde automatique indisponible : utilise « Sauvegarder ma progression ».');}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normalize(t){return t.normalize('NFC').trim().toLocaleLowerCase('de').replace(/[.!?]+$/,'').replace(/\s+/g,' ');}
function voices(){if(!('speechSynthesis'in window))return [];return window.speechSynthesis.getVoices().filter(v=>v.lang.startsWith('de'));}
function speak(t){if(!('speechSynthesis'in window)){status('Audio indisponible ici. Le texte et les exercices restent accessibles.');return;}const available=voices(),voice=available.find(v=>v.localService)||available[0];if(!voice){status('Aucune voix allemande disponible. Ajoute une voix allemande hors connexion dans les paramètres de ton appareil.');return;}if(!navigator.onLine&&!voice.localService){status('Cette voix nécessite Internet. Choisis une voix allemande locale dans les paramètres de ton appareil.');return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='de-DE';u.rate=.8;u.voice=voice;u.onerror=()=>status('La voix n’a pas pu lire cette phrase. Vérifie la voix allemande sur ton appareil.');window.speechSynthesis.speak(u);}
function audio(t){return `<button class="listen" data-speak="${esc(t)}" aria-label="Écouter ${esc(t)}">Écouter · DE</button>`;}
function navigation(){const count=LESSONS.filter((_,i)=>state.done[i]).length;document.querySelector('#overall').innerHTML=`${count} / ${LESSONS.length} leçons validées<div class="progress"><span style="width:${count/LESSONS.length*100}%"></span></div>`;document.querySelector('#lessons').innerHTML=LESSONS.map((l,i)=>`<button data-lesson="${i}" class="${view==='lesson'&&!reviewing&&i===current?'active':''}" ${view==='lesson'&&!reviewing&&i===current?'aria-current="page"':''}>${state.done[i]?'✓ ':''}${esc(l.title)}</button>`).join('');}
function getUnit(p){return BOOK_UNITS.find(u=>p>=u.start&&p<=u.end);}
function lessonLinks(indices){return indices.map(i=>`<button data-lesson="${i}">${esc(LESSONS[i].title)}</button>`).join('');}
function renderBook(){const p=state.page,u=getUnit(p),detail=VERIFIED_PAGES[p],progress=state.pages[p]||{},count=Object.values(state.pages).filter(x=>x.done).length;main.innerHTML=`<p class="tag">MON MANUEL · SUIVI PAGE PAR PAGE</p><h1>Une page, une séance.</h1><p>Commence à la page imprimée 8. Les pages du lecteur ont un décalage de +3 dans les repères vérifiés : livre 17 → lecteur 20.</p><form id="page-form" class="page-controls"><label for="book-page">Page imprimée</label><input id="book-page" type="number" min="1" max="255" value="${p}" required><button>Afficher</button><button type="button" id="prev-page" ${p===1?'disabled':''}>Précédente</button><button type="button" id="next-page" ${p===255?'disabled':''}>Suivante</button></form><section class="card"><p class="tag">PAGE ${p} · LECTEUR ${p+3}</p><h2>${esc(u?.title||'Pages préliminaires')}</h2><p class="notice">${detail?'Thème de cette page vérifié visuellement dans le manuel.':'Repère d’unité établi à partir du sommaire. Le contenu individuel de cette page n’a pas été vérifié ; les cours ci-dessous sont des compléments thématiques.'}</p>${detail?`<h3>Objectif de ta séance</h3><p>${esc(detail.goal)}</p><h3>Pratique personnelle</h3><p>${esc(detail.practice)}</p>`:'<p>Lis la page dans ton exemplaire. Note les mots inconnus, puis choisis un cours complémentaire. Le manuel et ses pistes audio ne sont pas inclus dans cette application.</p>'}<div class="choices"><a class="button-link" href="https://books.fliphtml5.com/uyqrj/vjiy/#p=${p+3}" target="_blank" rel="noopener">Ouvrir cette page en ligne ↗</a></div><h3>Cours originaux pour travailler ce thème</h3><div class="choices">${lessonLinks(detail?.lessons||u?.lessons||[])||'Aucun cours associé à cette annexe.'}</div><label for="page-notes"><b>Mes notes pour cette page</b></label><textarea id="page-notes" rows="5" maxlength="10000" placeholder="Mots nouveaux, questions et phrases à retenir…">${esc(progress.notes||'')}</textarea><p id="notes-status" class="small" aria-live="polite"></p><label class="check"><input type="checkbox" id="page-done" ${progress.done?'checked':''}> J’ai étudié cette page et refait ses exercices.</label><p class="small">${count} pages marquées comme étudiées. Ce suivi personnel ne remplace pas une évaluation.</p></section><details class="card"><summary>Choisir une unité du manuel</summary><div class="choices">${BOOK_UNITS.map(u=>`<button data-page="${u.start}">${esc(u.title)} · p. ${u.start}–${u.end}</button>`).join('')}</div></details>`;}
function questionMarkup(q,li,qi){const key=li+'-'+qi,ans=state.answers[key];let opts;if(q.typed)opts=`<form data-key="${key}"><label for="a${key}">Ta réponse</label><br><input id="a${key}" autocomplete="off" maxlength="400" required value="${esc(ans?.value||'')}" ${ans?'disabled':''}><button ${ans?'disabled':''}>Vérifier</button></form>`;else{const answers=[...q.answers],offset=(li+qi)%answers.length,arranged=answers.slice(offset).concat(answers.slice(0,offset));opts=`<div class="choices">${arranged.map(a=>`<button data-answer="${esc(a)}" data-key="${key}" ${ans?'disabled':''}>${esc(a)}</button>`).join('')}</div>`;}return `<div class="question"><h3>${esc(q.prompt)}</h3>${opts}<div aria-live="polite">${ans?`<p class="feedback ${ans.ok?'good':'bad'}">${ans.ok?'Correct !':'À retravailler.'} ${esc(q.why)}</p>`:''}</div>${reviewing&&ans&&!ans.ok?`<button data-retry-key="${key}">Réessayer cette question</button>`:''}</div>`;}
function render(){navigation();if(view==='book'){renderBook();return;}if(reviewing){main.innerHTML=`<p class="tag">RÉVISIONS</p><h1>Un peu mieux, chaque jour.</h1><p>Reprends les réponses qui t’ont posé problème.</p>${state.mistakes.length?state.mistakes.map(key=>{const[li,qi]=key.split('-').map(Number);return `<section class="card">${questionMarkup(LESSONS[li].questions[qi],li,qi)}</section>`;}).join(''):'<section class="card">Aucune erreur à réviser. Commence par les exercices d’une leçon.</section>'}`;return;}
const l=LESSONS[current];main.innerHTML=`<p class="tag">COURS ORIGINAL · A1 · 15–20 MIN</p><h1>${esc(l.title)}</h1><p class="intro">Aujourd’hui : ${esc(l.goal.toLowerCase())}.</p><p class="small">Ce cours complète ton manuel. Son numéro ne correspond pas à celui d’une unité du livre.</p><div class="tabs" aria-label="Étapes de la leçon">${[['cours','1. Comprendre'],['dialogue','2. Écouter & parler'],['exercices','3. M’entraîner']].map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'active':''}" aria-pressed="${tab===id}">${label}</button>`).join('')}</div><div id="content"></div>`;
const content=document.querySelector('#content');if(tab==='cours')content.innerHTML=`<section class="card"><h2>La règle, simplement</h2><p>${esc(l.rule)}</p></section><h2>Mes mots et expressions</h2><div class="grid">${l.vocab.map(([de,fr])=>`<article class="card"><div class="phrase" lang="de">${esc(de)}</div><div>${esc(fr)}</div>${audio(de)}</article>`).join('')}</div><section class="notice"><b>Prononciation</b> : écoute puis répète sans lire. « sch » ressemble au « ch » français ; « ei » à « aï » ; « ie » à un « i » long. Les sons ü et ö rappellent « u » et « eu ». Ce sont des repères approximatifs : compare avec une voix allemande.</section>`;
if(tab==='dialogue')content.innerHTML=`<section class="card dialog"><h2>Un petit échange</h2>${l.dialog.map(([de,fr])=>`<p lang="de"><b>${esc(de)}</b><br><span class="small">${esc(fr)}</span><br>${audio(de.substring(3))}</p>`).join('')}</section><section class="card"><h2>À toi de parler</h2><p>${esc(l.task)}</p><p class="small">Répète le dialogue, puis remplace les informations par les tiennes. L’application ne note pas automatiquement ta prononciation.</p></section>`;
if(tab==='exercices'){const answers=l.questions.map((_,i)=>state.answers[current+'-'+i]),complete=answers.every(Boolean),score=answers.filter(a=>a&&a.ok).length;content.innerHTML=`<section class="card"><h2>Teste-toi sans regarder le cours</h2>${l.questions.map((q,i)=>questionMarkup(q,current,i)).join('')}${complete?`<p class="feedback ${score>=4?'good':'bad'}">${score} / ${l.questions.length} réponses correctes. ${score>=4?'Leçon validée.':'Révise puis réessaie : il faut au moins 4 réponses correctes.'}</p>`:''}<div class="choices"><button id="retry">Recommencer les exercices</button>${state.done[current]&&current<LESSONS.length-1?'<button class="primary" id="next">Cours suivant</button>':''}</div></section>`;}}
function answer(key,value){if(!validKey(key)||state.answers[key])return;const[li,qi]=key.split('-').map(Number),q=LESSONS[li].questions[qi],ok=normalize(value)===normalize(q.correct);state.answers[key]={ok,value};state.mistakes=state.mistakes.filter(k=>k!==key);if(!ok)state.mistakes.push(key);const all=LESSONS[li].questions.map((_,i)=>state.answers[li+'-'+i]);if(all.every(Boolean)&&all.filter(a=>a.ok).length>=4)state.done[li]=true;save();const y=window.scrollY;render();window.scrollTo(0,y);}
function choosePage(p){if(!Number.isInteger(p)||p<1||p>255){status('Choisis une page entre 1 et 255.');return;}state.page=p;view='book';reviewing=false;save();render();}
function exportProgress(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='deutsch-progression.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Progression exportée. Garde ce fichier pour la restaurer sur un autre appareil.');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.speak!==undefined){speak(b.dataset.speak);return;}if(b.dataset.lesson!==undefined){current=Number(b.dataset.lesson);if(!LESSONS[current])return;view='lesson';tab='cours';reviewing=false;render();}else if(b.dataset.page){choosePage(Number(b.dataset.page));}else if(b.dataset.tab){tab=b.dataset.tab;render();}else if(b.dataset.answer!==undefined){answer(b.dataset.key,b.dataset.answer);}else if(b.dataset.retryKey){delete state.answers[b.dataset.retryKey];save();render();}else if(b.id==='retry'){LESSONS[current].questions.forEach((_,i)=>delete state.answers[current+'-'+i]);save();render();}else if(b.id==='next'&&current<LESSONS.length-1){current++;tab='cours';render();window.scrollTo(0,0);}else if(b.id==='review'){reviewing=true;view='lesson';state.mistakes.forEach(k=>delete state.answers[k]);save();render();}else if(b.id==='book'){view='book';reviewing=false;render();}else if(b.id==='prev-page'){choosePage(state.page-1);}else if(b.id==='next-page'){choosePage(state.page+1);}else if(b.id==='export'){exportProgress();}});
document.addEventListener('submit',e=>{if(e.target.id==='page-form'){e.preventDefault();choosePage(Number(document.querySelector('#book-page').value));}else if(e.target.dataset.key){e.preventDefault();answer(e.target.dataset.key,e.target.querySelector('input').value);}});
document.addEventListener('input',e=>{if(e.target.id==='page-notes'){state.pages[state.page]={...state.pages[state.page],notes:e.target.value};save();document.querySelector('#notes-status').textContent=storageOK?'Notes enregistrées.':'Notes en mémoire : exporte ta progression pour les conserver.';}});
document.addEventListener('change',async e=>{if(e.target.id==='page-done'){state.pages[state.page]={...state.pages[state.page],done:e.target.checked};save();render();}if(e.target.id==='import'){const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error('Fichier trop grand');const incoming=cleanState(JSON.parse(await file.text()));if(!confirm('Remplacer la progression actuelle par celle de ce fichier ?'))return;state=incoming;save();render();status('Progression restaurée.');}catch{status('Fichier de progression invalide. La progression actuelle est conservée.');}finally{e.target.value='';}}});
function updateConnection(){document.querySelector('#connection').textContent=navigator.onLine?'Cours disponibles localement · Manuel en ligne':'Hors connexion · Cours et exercices disponibles';const local=voices().some(v=>v.localService);document.querySelector('#voice-status').textContent=local?'Voix allemande locale détectée.':'Audio hors connexion : une voix allemande locale doit être installée sur ton appareil.';}
window.addEventListener('online',updateConnection);window.addEventListener('offline',updateConnection);if('speechSynthesis'in window)window.speechSynthesis.addEventListener('voiceschanged',updateConnection);
render();updateConnection();if(!storageOK)status('La sauvegarde automatique n’a pas pu être lue. Exporte ta progression pour la conserver.');
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{document.querySelector('#cache-status').textContent='Application prête pour le hors connexion sur cette adresse.';}).catch(()=>{document.querySelector('#cache-status').textContent='Installation hors connexion indisponible ici. Utilise le fichier Deutsch-A1-hors-connexion.html.';});
